### ISSUE TITLE
Not so much an issue as a networking question

### ISSUE THREAD

**Issue by TeddyRandby** [deepcake/echo#4]
I'm trying to do some networking with hxbit as well and am running into issues in my implementation on a conceptual level. I can serialize and unserialize the entities and views well enough, but plugging them back into the workflow on the client side doesn't seem to be possible. Is there a way to mass-add entities and views at a low level, when I just have the Entity(Int) Arrays I need?

**Comment by deepcake** [comment]
I will try to help.

It makes no sense to serialize `Entity`, since the `Entity` class is just an `Int`, not unique all the time, fully for internal needs, without storing components.

Instead of serializing `Entity`, you need to serialize its components.
So on the server and on the clients their own `Entities` should be created, but with synchronized components.

I should also mention that `echoes` are based on static variables, what I think will have a very bad effect on server scaling.

**Comment by TeddyRandby** [comment]
Thanks! That clears things up and makes more sense. Your source code is very clean and readable and that has been a huge help as well. Serializing and syncing the components is working - but I've ran into a problem with recreating entities. I have it hard-coded now in my simple example to just add the same entities on the client and server side- but when there are different types of entities being dynamically created, the client won't know which entities to add, out of which components.

Once again, thanks for bearing with me and being helpful!

**Comment by TeddyRandby** [comment]
I figured it out using RPCs. Thanks for the help!
